name: Build and Push to Aliyun

on:
  push:
    branches: [ "main" ]  # 当 main 分支有变动时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALiyun_REGISTRY }}
          username: ${{ secrets.ALiyun_USERNAME }}
          password: ${{ secrets.ALiyun_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # 这里换成你自己的镜像全路径
          tags: ${{ secrets.ALiyun_REGISTRY }}/jiangnan5210/musicn:latest
